ALTER TABLE külastajad ADD CONSTRAINT fk_külastaja_2_seanss
FOREIGN KEY (seanss)
REFERENCE seansid(id)
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE tellimused ADD CONSTRAINT fk_tellimus_2_toit
FOREIGN KEY (toit)
REFERENCE toidud(id)
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE tellimused ADD CONSTRAINT fk_tellimus_2_tellija
FOREIGN KEY (tellija)
REFERENCE külastajad(id)
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE kinosaalid ADD CONSTRAINT fk_kinosaal_2_kino
FOREIGN KEY (kino)
REFERENCE kinod(id)
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE kinosaalid ADD CONSTRAINT fk_kinosaal_2_saal
FOREIGN KEY (saal)
REFERENCE saalid(id)
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE seansid ADD CONSTRAINT fk_seanss_2_saal
FOREIGN KEY (saal)
REFERENCE kinosaalid(id)
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE seansid ADD CONSTRAINT fk_seanss_2_film
FOREIGN KEY (film)
REFERENCE filmid(id)
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE kinoseansid ADD CONSTRAINT fk_kinoseanss_2_kino
FOREIGN KEY (kino)
REFERENCE kinod(id)
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE kinoseansid ADD CONSTRAINT fk_kinoseanss_2_seanss
FOREIGN KEY (seanss)
REFERENCE seansid(id)
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE sissetulekud ADD CONSTRAINT fk_sissetulek_2_kino
FOREIGN KEY (kino)
REFERENCE kinod(id)
ON DELETE RESTRICT ON UPDATE CASCADE;